name: BIGACE Web CMS
markdown: redcarpet
relative_permalinks: false
docu_url: http://wiki.bigace.de
forum_url: http://forum.bigace.de
download_url: /download.html
tools_url: http://dev.bigace.de/tools
api_url: http://dev.bigace.de/api/latest/
image_url: http://www.bigace.de/hoster
issue_url: https://github.com/bigace/bigace2/issues
github_url: https://github.com/bigace/
plugins_url: http://plugins.bigace.de
v3_latest_version: 3.0
v3_latest_date: 2015-07-26
v3_download_latest: http://plugins.bigace.de/plugins/get/225-Bigace
permalink: /news/:title
gems:
  - jekyll-redirect-from
  - jekyll-sitemap