name: BIGACE Web CMS
markdown: kramdown
relative_permalinks: false
docu_url: http://wiki.bigace.de
forum_url: http://forum.bigace.de
download_url: /download.html
tools_url: http://dev.bigace.de/tools
image_url: /images
issue_url: https://github.com/bigace/bigace2/issues
github_url: https://github.com/bigace/
plugins_url: https://github.com/bigace/plugin-releases/
v3_latest_version: 3.0
v3_latest_date: 2015-07-26
v3_download_latest: https://github.com/bigace/bigace3/files/1405012/bigace_3.0.zip
permalink: /news/:title
gems:
  - jekyll-redirect-from
  - jekyll-sitemap