name: Kimai Time-Tracking
markdown: redcarpet
relative_permalinks: false
docu_url: http://www.kimai.org/documentation/
forum_url: http://forum.kimai.org/
download_url: /download/
issues_url: https://github.com/kimai/kimai/issues
stable_url: https://github.com/kimai/kimai/releases/download/0.9.3/kimai_0.9.3.zip
permalink: /blog/:year/:title/
gems:
  - jekyll-redirect-from
  - jekyll-sitemap